### ISSUE TITLE
Invalid option update interval

### ISSUE THREAD

**Issue by Styx85** [brandond/esphome-tuya_pir#5]
Hi there.
With latest esphome and your code I'm getting this config error.

> caberliner@pop-os:~/.local/bin$ python esphome /home/caberliner/.local/bin/test/pir2.yaml run
> INFO Reading configuration...
> Failed config
> 
> binary_sensor.template: [source /home/caberliner/.local/bin/test/pir2.yaml:77]
>   platform: template
>   id: motion
>   name: PIR2
>   
>   [update_interval] is an invalid option for [binary_sensor.template]. Did you mean [internal]?
>   update_interval: never [source /home/caberliner/.local/bin/test/pir2.yaml:80]
>   filters: []
>   device_class: motion
>   lambda: return {};

The problematic code is this line:

> binary_sensor:
>   - platform: template
>     id: motion
>     name: "PIR2"
>     **update_interval: never**
>     filters: []
>     device_class: motion
>     lambda: "return {};"

Without the line update interval it is working correctly.

**Comment by itProfi** [comment]
Yes, the same problem!

**Comment by brandond** [comment]
I think that must have been removed at some point. I'll update the sample.
