### ISSUE TITLE
NEO Coolcam Wifi PIR tuya firmware schema

### ISSUE THREAD

**Issue by garynl** [brandond/esphome-tuya_pir#8]
Does anyone have the schema used by the Tuya firmware?

**Comment by brandond** [comment]
Schema as in the flash layout? I have some dumped bins from bother the PIR and door sensors I can share.

**Comment by garynl** [comment]
If you could share the bin for the PIR I'd be grateful.

**Comment by brandond** [comment]
Hopefully this won't get me in trouble.
[pir.zip](https://github.com/brandond/esphome-tuya_pir/files/3852942/pir.zip)

**Comment by garynl** [comment]
🤐😏

**Comment by brandond** [comment]
Let me know if you do anything fun with it ;)
